[package]
name = "shunting_yard-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
shunting_yard = { path = ".." }

[[bin]]
name = "evaluate"
path = "fuzz_targets/evaluate.rs"
test = false
doc = false
bench = false

[[bin]]
name = "evaluate_no_panic"
path = "fuzz_targets/evaluate_no_panic.rs"
test = false
doc = false
bench = false
