name: fuzz

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  fuzz-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-fuzz

      - name: Build evaluate_no_panic fuzz target
        working-directory: crates/shunting-yard/fuzz
        run: cargo fuzz build evaluate_no_panic
